In [1]:
import os
import numpy as np
import cv2 as cv
import dlib
%matplotlib inline
import matplotlib.pyplot as plt
face_detector = dlib.get_frontal_face_detector()
main_path='downloads'
predictor_model="shape_predictor_68_face_landmarks.dat"
predictor = dlib.shape_predictor(predictor_model)
facerec=dlib.face_recognition_model_v1('dlib_face_recognition_resnet_model_v1.dat')
d=os.listdir(main_path)
img_array=[]
img_labels=[]

for i,dirs in enumerate(sorted(d)):
    if(dirs.endswith('specs')):
        
        
        for item in (os.listdir(main_path+'/'+dirs)):
            #print(item)
            label=[0,0]
            if(item.endswith('.jpg')):
                img=cv.imread(main_path+'/'+dirs+'/'+item)
                try:
                    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

                    face_rect= face_detector(gray, 1)


                    for k,d in enumerate(face_rect):
                        shape=predictor(gray,d)
                        face_descriptor = facerec.compute_face_descriptor(img,shape )
                    #rect=cv.rectangle(img, (x, y), (x + w, y + h), (0, 255, 0), 2)
                    #rect = img[y:y+h,x:x+w]
                    label[i-1]=1
                    img_array.append(face_descriptor)
                    img_labels.append(label)
                except Exception as e:
                    print(e)
        
            
img_dataset=np.array(img_array)
img_labell=np.array(img_labels)
print(img_dataset.shape)
print(img_labell.shape)

name 'face_descriptor' is not defined
/Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/color.cpp:11111: error: (-215) scn == 3 || scn == 4 in function cvtColor

(68, 128)
(68, 2)


In [2]:
img_dataset[1].shape


(128,)

In [3]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(img_dataset, img_labell, test_size = 0.20)
from keras.models import Sequential
from keras.layers import Dense
from keras import optimizers
model = Sequential()
model.add(Dense(512, input_dim=128, activation='sigmoid'))
model.add(Dense(512, activation='sigmoid'))
model.add(Dense(2, activation='softmax'))
#sgd = optimizers.SGD(lr=0.063, decay=0.9)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


/Users/avisheksarkar/anaconda/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [7]:
model.fit(X_train, y_train, epochs=20, shuffle=True)

Epoch 1/20
54/54 [==============================] - 0s 755us/step - loss: 0.6367 - acc: 0.5741
Epoch 2/20
54/54 [==============================] - 0s 595us/step - loss: 0.6412 - acc: 0.6296
Epoch 3/20
54/54 [==============================] - 0s 562us/step - loss: 0.6398 - acc: 0.5741
Epoch 4/20
54/54 [==============================] - 0s 449us/step - loss: 0.6300 - acc: 0.5741
Epoch 5/20
54/54 [==============================] - 0s 377us/step - loss: 0.6247 - acc: 0.7593
Epoch 6/20
54/54 [==============================] - 0s 558us/step - loss: 0.6287 - acc: 0.8148
Epoch 7/20
54/54 [==============================] - 0s 370us/step - loss: 0.6182 - acc: 0.7037
Epoch 8/20
54/54 [==============================] - 0s 308us/step - loss: 0.6339 - acc: 0.5741
Epoch 9/20
54/54 [==============================] - 0s 481us/step - loss: 0.6145 - acc: 0.6296
Epoch 10/20
54/54 [==============================] - 0s 582us/step - loss: 0.6267 - acc: 0.7778
Epoch 11/20
54/54 [==============================

In [8]:
alpha=['yes','no']
cap = cv.VideoCapture(0)
ret,frame=cap.read()
while ret:
    ret, frame = cap.read()
    gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
#image=os.getcwd()+'/test_images/srija_test.jpeg'
#image=cv.imread(image)
#gray = cv.cvtColor(image, cv.COLOR_BGR2GRAY)
    detected_faces = face_detector(gray, 1)
    if(detected_faces):
        for i,face_rect in enumerate(detected_faces):
            shape=predictor(gray,face_rect)
            face_descriptor = facerec.compute_face_descriptor(frame,shape)
            face_descriptor=np.array(face_descriptor)
            face_descriptor=face_descriptor.reshape((-1,1*128)).astype(np.float32)
            print(model.predict(face_descriptor))

[[0.31835738 0.6816426 ]]
[[0.3179458  0.68205416]]
[[0.32827336 0.67172664]]
[[0.36497483 0.63502514]]
[[0.314883   0.68511707]]
[[0.32688203 0.6731179 ]]
[[0.31996793 0.680032  ]]
[[0.33795333 0.6620467 ]]
[[0.3626774 0.6373226]]
[[0.29476222 0.7052378 ]]
[[0.36639065 0.63360935]]
[[0.35631165 0.6436884 ]]
[[0.31755224 0.68244773]]
[[0.34498912 0.6550109 ]]
[[0.38360432 0.6163957 ]]


KeyboardInterrupt: 